# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-26 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_link',
            field=models.TextField(null=True),
        ),
    ]
