# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0002_auto_20190720_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_message',
        ),
        migrations.AddField(
            model_name='comment',
            name='the_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='userDashboard.Message'),
        ),
    ]
