# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0004_auto_20190720_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_to', to='userDashboard.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='the_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='userDashboard.Message'),
        ),
    ]
